### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jorged** [d4rkr00t/css-comb-atom#112]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [css-comb](https://github.com/d4rkr00t/css-comb-atom) package 2.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/minimatch/minimatch.js:717

TypeError: Cannot read property 'split' of undefined
    at Minimatch.match (/Applications/Atom.app/Contents/Resources/app/node_modules/minimatch/minimatch.js:717:8)
    at minimatch (/Applications/Atom.app/Contents/Resources/app/node_modules/minimatch/minimatch.js:107:42)
    at /packages/css-comb/lib/css-comb.js:272:38
    at Array.some (native)
    at CssComb._isIgnored (/packages/css-comb/lib/css-comb.js:271:20)
    at CssComb.comb (/packages/css-comb/lib/css-comb.js:90:14)
    at /packages/css-comb/lib/css-comb.js:44:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:24.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -0:19 css-comb:run (div.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-html-preview 0.1.22 
autocomplete-html-entities 0.1.0 
color-picker 2.2.5 
css-comb 2.5.0 
emmet 2.4.3 
file-icons 2.1.6 
formatter 2.12.4 
git-plus 7.9.2 
javascript-snippets 1.2.1 
merge-conflicts 1.4.5 
pretty-json 1.6.3 
xml-formatter 0.10.0 
```

**Comment by DHBuild002** [comment]
Hi Jorged,

I have just come up against this problem too!
My resolution was very simple though. I had simply forgotten to save the file I was combing as a .css file. So the program did not recognise the code format.

What is the name of the file you are attempting to comb?
