### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActivePaneItem(...).getPath is not a function

### ISSUE THREAD

**Issue by csantiago132** [d4rkr00t/css-comb-atom#15]
[Enter steps to reproduce below:]
1. I type ctrl-alt-c and this happens

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [css-comb](https://github.com/d4rkr00t/css-comb-atom) package, v2.4.0
### Stack Trace

Uncaught TypeError: atom.workspace.getActivePaneItem(...).getPath is not a function

```
At /Users/Carlos/.atom/packages/css-comb/lib/css-comb.js:75

TypeError: atom.workspace.getActivePaneItem(...).getPath is not a function
    at CssComb.comb (/Users/Carlos/.atom/packages/css-comb/lib/css-comb.js:75:55)
    at atom-workspace.cssCombRun (/Users/Carlos/.atom/packages/css-comb/lib/css-comb.js:40:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -5:53.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:52.5.0 core:save (atom-text-editor.editor.is-focused)
     -5:48 core:move-down (atom-text-editor.editor.is-focused)
     -5:47.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -5:47.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:46.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -5:46.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:46 core:save (atom-text-editor.editor.is-focused)
     -5:41 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -5:41 editor:newline (atom-text-editor.editor.is-focused)
     -5:40.1.0 core:save (atom-text-editor.editor.is-focused)
     -4:05.7.0 core:copy (table.package-keymap-table.table.native-key-bindings.text)
     -0:44.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:44.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:43.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.1.0 css-comb:run (input#css-comb.showNotifications.)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "css-comb": {
    "shouldUpdateOnSave": true,
    "showNotifications": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.19
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.1
autoclose-html, v0.19.0
css-comb, v2.4.0
emmet, v2.3.17
file-icons, v1.6.13

# Dev
No dev packages
```

**Comment by d4rkr00t** [comment]
Hi, thank you, I'll take a look.

**Comment by d4rkr00t** [comment]
It looks like the same issue as https://github.com/atom/atom/issues/2407 but I'm not sure. There was suggested removing the `~/.atom/storage` folder, please try to do so and let me know if that doesn't help.

**Comment by d4rkr00t** [comment]
Hi! Does this issue still actual?

**Comment by xylix** [comment]
@d4rkr00t I just got this error.

**Comment by silverliebt** [comment]
[Enter steps to reproduce:]

1. Run csscomb on save is enabled
2. copied a .csscomb.json file to working directory
3. Ctr + S to save, received error below
4. Closed file, upon reopen and resave error does not repeat

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [css-comb](https://github.com/d4rkr00t/css-comb-atom) package 2.5.0

`
### Stack Trace

Uncaught TypeError: atom.workspace.getActivePaneItem(...).getPath is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1095

TypeError: atom.workspace.getActivePaneItem(...).getPath is not a function
    at CssComb.comb (/packages/css-comb/lib/css-comb.js:83:55)
    at /packages/css-comb/lib/css-comb.js:70:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1119:26)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:780:24)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:44.3.0 core:paste (input.hidden-input)
  4x -9:36.7.0 editor:newline (input.hidden-input)
     -9:00.1.0 core:backspace (input.hidden-input)
     -8:38.1.0 core:paste (input.hidden-input)
     -8:29.5.0 core:save (input.hidden-input)
     -8:11.4.0 css-comb:run (input.hidden-input)
     -7:56.5.0 core:save-as (input.hidden-input)
     -7:11.9.0 application:open (input.hidden-input)
     -6:45.1.0 core:save-as (input.hidden-input)
  2x -6:22.4.0 core:save (div.tool-panel.tree-view)
     -5:41.1.0 core:close (input.hidden-input)
     -5:37.2.0 core:save (input.hidden-input)
  3x -4:17.6.0 core:backspace (input.hidden-input)
     -4:04.2.0 core:save (input.hidden-input)
     -0:37.2.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:36.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-css-clean 2.20.5 
autoprefixer 3.7.0 
busy-signal 1.4.3 
count-word 0.2.3 
css-comb 2.5.0 
cssbeautify 1.3.0 
cssnano 1.1.0 
emmet 2.4.3 
gtk-dark-theme 0.1.4 
intentions 1.1.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-ui-default 1.6.0 
open-in-browser 0.5.2 
open-recent 5.0.0 
pigments 0.39.1 
todo-show 1.11.0 
wrap 0.1.0 
```
`
