### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/nils/.atom/packages/atom-css-comb/node_modules/csscomb/lib/options'

### ISSUE THREAD

**Issue by nilshendriks** [d4rkr00t/css-comb-atom#2]
Hi, this is the error I got when I first tried.

I turned off searching for the config file and directed it to the full path and now it works.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [css-comb](https://github.com/d4rkr00t/css-comb-atom) package, v1.1.1
### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/nils/.atom/packages/atom-css-comb/node_modules/csscomb/lib/options'

```
At fs.js:691

Error: ENOENT, no such file or directory '/Users/nils/.atom/packages/atom-css-comb/node_modules/csscomb/lib/options'
  at Error (native)
  at Object.fs.readdirSync (fs.js:691:18)
  at Object.fs.readdirSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:398:26)
  at new CSScomb (/Users/nils/.atom/packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:161:22)
  at Object.module.exports._processFile (/Users/nils/.atom/packages/css-comb/lib/css-comb.coffee:75:16)
  at Object.module.exports.comb (/Users/nils/.atom/packages/css-comb/lib/css-comb.coffee:63:8)
  at atom-workspace.subscriptions.add.atom.commands.add.css-comb:run (/Users/nils/.atom/packages/css-comb/lib/css-comb.coffee:49:80)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```
### Commands

```
     -6:03.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:57.3 core:confirm (atom-text-editor.editor.mini)
     -5:57.3 css-comb:comb (atom-text-editor.editor.is-focused)
     -5:55.6 core:select-all (atom-text-editor.editor.is-focused)
     -5:54.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:52.9 core:confirm (atom-text-editor.editor.mini)
     -5:52.9 css-comb:comb (atom-text-editor.editor.is-focused)
     -5:29.0 settings-view:open (atom-text-editor.editor.is-focused)
     -5:27.2 command-palette:toggle (div.settings-view.pane-item)
     -5:25.3 core:move-down (atom-text-editor.editor.mini)
     -5:24.9 core:confirm (atom-text-editor.editor.mini)
     -5:24.9 settings-view:uninstall-packages (div.settings-view.pane-item)
     -5:03.3 core:backspace (atom-text-editor.editor.mini)
     -5:01.1 core:confirm (atom-text-editor.editor.mini)
  3x -0:04.3 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.8 css-comb:run (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "expand-selection",
      "project-palette-finder"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "css-comb": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v1.1.0
color-gutter, v0.3.1
color-picker, v1.4.4
css-comb, v1.1.1
dash, v1.0.2
emmet, v2.3.2
highlight-line, v0.9.3
language-jade, v0.3.0
linter, v0.10.1
linter-htmlhint, v0.0.8
linter-jshint, v0.1.0
linter-scss-lint, v0.0.11
numbers-on-a-pane, v0.1.0
pdf-view, v0.14.0
project-manager, v1.15.4
set-syntax, v0.2.0
seti-syntax, v0.2.1
seti-ui, v0.6.3
tasks, v1.2.4

# Dev
No dev packages
```

/cc @atom/core

**Comment by d4rkr00t** [comment]
Thanks for bug report, I'll try to fix it)

**Comment by d4rkr00t** [comment]
Hm, it seems like you didn't have fully installed csscomb at first try (it's strange cause it should be installed with plugin), but if it works now, you probably can enable searching for the config file and it should work.
